#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/ConfirmDialog.cshtml")]
    public partial class ConfirmDialog : System.Web.Mvc.WebViewPage<NotLimited.Framework.Web.Controls.Model.ConfirmDialogModel>
    {
        public ConfirmDialog()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n<script type=\"text/javascript\">\r\n\tfunction ConfirmDialog() {\r\n\t\t$(\'#");


            
            #line 7 "..\..\Views\Shared\ConfirmDialog.cshtml"
 Write(Model.DialogId);

            
            #line default
            #line hidden
WriteLiteral("\').modal(\'show\');\r\n\t}\r\n\r\n\tfunction SubmitConfirmed() {\r\n\t\t$(\'#");


            
            #line 11 "..\..\Views\Shared\ConfirmDialog.cshtml"
 Write(Model.FormId);

            
            #line default
            #line hidden
WriteLiteral("\').submit();\r\n\t}\r\n</script>\r\n\r\n<div class=\"modal fade\" id=\"");


            
            #line 15 "..\..\Views\Shared\ConfirmDialog.cshtml"
                       Write(Model.DialogId);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <div class=\"modal-dialog\">\r\n        <div class=\"modal-content\">\r\n        " +
"    <div class=\"modal-header\">\r\n                <a href=\"#\" class=\"close\" data-d" +
"ismiss=\"modal\" aria-hidden=\"true\">×</a>\r\n                <h4 class=\"modal-title\"" +
">");


            
            #line 20 "..\..\Views\Shared\ConfirmDialog.cshtml"
                                   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n            </div>\r\n\r\n            <div class=\"modal-body\">\r\n              " +
"  ");


            
            #line 24 "..\..\Views\Shared\ConfirmDialog.cshtml"
           Write(Model.Text);

            
            #line default
            #line hidden
WriteLiteral(@"
            </div>

            <div class=""modal-footer"">
                <button type=""button"" class=""btn btn-default"" data-dismiss=""modal"">Отмена</button>
                <button type=""button"" class=""btn btn-primary"" data-dismiss=""modal"" onclick=""SubmitConfirmed();"">ОК</button>
            </div>
        </div>
    </div>
</div>

");


        }
    }
}
#pragma warning restore 1591
