#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NotLimited.Framework.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/ConfirmDialog.cshtml")]
    public partial class ConfirmDialog : System.Web.Mvc.WebViewPage<NotLimited.Framework.Web.Controls.Model.ConfirmDialogModel>
    {
        public ConfirmDialog()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n");

WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\tfunction ConfirmDialog() {\r\n\t\t$(\'#");

       Write(Model.DialogId);

WriteLiteral("\').modal(\'show\');\r\n\t}\r\n\r\n\tfunction SubmitConfirmed() {\r\n\t\t$(\'#");

       Write(Model.FormId);

WriteLiteral("\').submit();\r\n\t}\r\n</script>\r\n\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteAttribute("id", Tuple.Create(" id=\"", 371), Tuple.Create("\"", 391)
, Tuple.Create(Tuple.Create("", 376), Tuple.Create<System.Object, System.Int32>(Model.DialogId
, 376), false)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</a>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">");

                                   Write(Model.Title);

WriteLiteral("</h4>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

           Write(Model.Text);

WriteLiteral("\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Отмена</button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"SubmitConfirmed();\"");

WriteLiteral(">ОК</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
