#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Paginator.cshtml"
    using NotLimited.Framework.Web.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Paginator.cshtml")]
    public partial class Paginator : System.Web.Mvc.WebViewPage<NotLimited.Framework.Data.Queries.Pagination>
    {
        public Paginator()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");


            
            #line 6 "..\..\Views\Shared\Paginator.cshtml"
 if ((double)Model.TotalCount / Model.ItemsPerPage > 1)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"text-center\">\r\n        <ul class=\"pagination\">\r\n");


            
            #line 10 "..\..\Views\Shared\Paginator.cshtml"
             foreach (var page in Enumerable.Range(1, (int)Math.Ceiling((double)Model.TotalCount / Model.ItemsPerPage)))
            {

            
            #line default
            #line hidden
WriteLiteral("                <li class=\"");


            
            #line 12 "..\..\Views\Shared\Paginator.cshtml"
                       Write(page == Model.Page ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    ");


            
            #line 13 "..\..\Views\Shared\Paginator.cshtml"
               Write(Html.ActionLink((page).ToString(), null, Html.AppendQueryString(new { page })));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n");


            
            #line 15 "..\..\Views\Shared\Paginator.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </div>\r\n");


            
            #line 18 "..\..\Views\Shared\Paginator.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
