#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class FormHelpers
    {

public static System.Web.WebPages.HelperResult TextBox(MvcHtmlString label, MvcHtmlString textBox, MvcHtmlString validation)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 4 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"form-group\">\r\n        ");



#line 6 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, label);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        ");



#line 7 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, textBox);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        ");



#line 8 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, validation);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    </div>\r\n");



#line 10 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Upload(MvcHtmlString label, string inputName, MvcHtmlString validation, string accept = "image/*")
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 13 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"form-group\">\r\n        ");



#line 15 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, label);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        <input type=\"file\" class=\"form-control\" name=\"");



#line 16 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
           WebViewPage.WriteTo(@__razor_helper_writer, inputName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" id=\"");



#line 16 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
                           WebViewPage.WriteTo(@__razor_helper_writer, inputName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" accept=\"");



#line 16 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
                                               WebViewPage.WriteTo(@__razor_helper_writer, accept);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n        ");



#line 17 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, validation);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    </div>\r\n");



#line 19 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult SubmitButton(string text)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 22 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <button type=\"submit\" class=\"btn btn-primary\">");



#line 23 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"
       WebViewPage.WriteTo(@__razor_helper_writer, text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</button>\r\n");



#line 24 "..\..\Views\Shared\Helpers\FormHelpers.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
