#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
    using NotLimited.Framework.Data.Queries;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
    using NotLimited.Framework.Web.Controls;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
    using NotLimited.Framework.Web.Controls.Grid;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
    using NotLimited.Framework.Web.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class GridViewHelper
    {

public static System.Web.WebPages.HelperResult GridScript()
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 9 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, @"    <script>
    $(function () {
        $(""th.sortable"").click(function () {
            SortGrid($(this).data(""name""), $(this).data(""descending""));
        });
    });

    function SortGrid(name, descending) {
        $(""#gridSort #sortBy"").val(name);
        $(""#gridSort #descending"").val(descending);
        $(""#gridSort"").submit();
    }
    </script>
");



#line 23 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Grid(HtmlHelper htmlHelper, List<HelperResult> headers, List<List<HelperResult>> rows, GridFormBuilder formBuilder, Pagination pagination, object tableHtmlAttributes)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 26 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
 
    using (htmlHelper.BeginForm(null, null, FormMethod.Get, new {id = "gridSort"}))
    {
        
#line default
#line hidden


#line 29 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlHelper.TextBox("sortBy", "", new {style = "display: none;"}));

#line default
#line hidden


#line 29 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                                                                         
        
#line default
#line hidden


#line 30 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlHelper.TextBox("descending", "", new { style = "display: none;" }));

#line default
#line hidden


#line 30 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                                                                               
        
#line default
#line hidden


#line 31 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlHelper.Form().HiddenForQuery("sortBy", "descending"));

#line default
#line hidden


#line 31 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                                                                 
    }

    using (htmlHelper.BeginForm(formBuilder.FormAction, formBuilder.FormController, formBuilder.FormMethod, new {id = formBuilder.FormId}))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <table ");



#line 36 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlHelper.RenderHtmlAttributes(tableHtmlAttributes));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n            <thead>\r\n                <tr>\r\n");



#line 39 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                     foreach (var header in headers)
                    {
                        
#line default
#line hidden


#line 41 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, header);

#line default
#line hidden


#line 41 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                               
                    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </tr>\r\n            </thead>\r\n            <tbody>\r\n            \r\n");



#line 47 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                 foreach (var row in rows)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <tr>\r\n");



#line 50 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                         foreach (var column in row)
                        {
                            
#line default
#line hidden


#line 52 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, column);

#line default
#line hidden


#line 52 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                                   
                        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    </tr>\r\n");



#line 55 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </tbody>\r\n        </table>\r\n");



#line 58 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"

        if (formBuilder.FormControls != null)
        {
            
#line default
#line hidden


#line 61 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, formBuilder.FormControls(null));

#line default
#line hidden


#line 61 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                                           
        }
    }

    if (pagination != null)
    {
        
#line default
#line hidden


#line 67 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlHelper.Partial("Paginator", pagination));

#line default
#line hidden


#line 67 "..\..\Views\Shared\Helpers\GridViewHelper.cshtml"
                                                    
    }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
