#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NotLimited.Framework.Data.Queries;
    using NotLimited.Framework.Web;
    using NotLimited.Framework.Web.Controls;
    using NotLimited.Framework.Web.Controls.Grid;
    using NotLimited.Framework.Web.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal class GridViewHelper : System.Web.WebPages.HelperPage
    {

#line default
#line hidden
public static System.Web.WebPages.HelperResult GridScript()
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, @"    <script>
    $(function () {
        $(""th.sortable"").click(function () {
            SortGrid($(this).data(""name""), $(this).data(""descending""));
        });
    });

    function SortGrid(name, descending) {
        $(""#gridSort #sortBy"").val(name);
        $(""#gridSort #descending"").val(descending);
        $(""#gridSort"").submit();
    }
    </script>
");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Grid(HtmlHelper htmlHelper, List<HelperResult> headers, List<List<HelperResult>> rows, Func<IDisposable> form, Func<object, HelperResult> formControls, Pagination pagination, object tableHtmlAttributes)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
    using (htmlHelper.BeginForm(null, null, FormMethod.Get, new {id = "gridSort"}))
    {
        
WriteTo(__razor_helper_writer, htmlHelper.Form().Hidden("sortBy", ""));

                                               
        
WriteTo(__razor_helper_writer, htmlHelper.Form().Hidden("descending", ""));

                                                   
        
WriteTo(__razor_helper_writer, htmlHelper.Form().HiddenForQuery("sortBy", "descending"));

                                                                 
    }
    

WriteLiteralTo(__razor_helper_writer, "    <div></div>\r\n");


    using (form != null ? form() : new DummyForm())
    {

WriteLiteralTo(__razor_helper_writer, "        <table ");

WriteTo(__razor_helper_writer, htmlHelper.RenderHtmlAttributes(tableHtmlAttributes));

WriteLiteralTo(__razor_helper_writer, ">\r\n            <thead>\r\n                <tr>\r\n");

                    
                     foreach (var header in headers)
                    {
                        
WriteTo(__razor_helper_writer, header);

                               
                    }

WriteLiteralTo(__razor_helper_writer, "                </tr>\r\n            </thead>\r\n            <tbody>\r\n            \r\n");

                
                 foreach (var row in rows)
                {

WriteLiteralTo(__razor_helper_writer, "                    <tr>\r\n");

                        
                         foreach (var column in row)
                        {
                            
WriteTo(__razor_helper_writer, column);

                                   
                        }

WriteLiteralTo(__razor_helper_writer, "                    </tr>\r\n");

                }

WriteLiteralTo(__razor_helper_writer, "            </tbody>\r\n        </table>\r\n");


        if (formControls != null)
        {
            
WriteTo(__razor_helper_writer, formControls(null));

                               
        }
    }

    if (pagination != null)
    {
        
WriteTo(__razor_helper_writer, htmlHelper.Partial("Paginator", pagination));

                                                    
    }

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult TableHeader(System.Web.Mvc.HtmlHelper helper, PropertyMetadata prop, string title, TableHelpers.SortOrder sortOrder)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
    if (prop.Sortable)
    {

WriteLiteralTo(__razor_helper_writer, "        <th");

WriteLiteralTo(__razor_helper_writer, " class=\"sortable\"");

WriteLiteralTo(__razor_helper_writer, " data-name=\"");

          WriteTo(__razor_helper_writer, prop.PropertyInfo.Name);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-descending=\"");

                                                    WriteTo(__razor_helper_writer, TableHelpers.IsOppositeOrderDescending(sortOrder).ToString());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "            ");

WriteTo(__razor_helper_writer, title);

WriteLiteralTo(__razor_helper_writer, "\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"pull-right\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <span");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 2498), Tuple.Create("\"", 2545)
, Tuple.Create(Tuple.Create("", 2506), Tuple.Create("fa", 2506), true)
, Tuple.Create(Tuple.Create(" ", 2508), Tuple.Create<System.Object, System.Int32>(TableHelpers.GetSortIcon(sortOrder)
, 2509), false)
);

WriteLiteralTo(__razor_helper_writer, " style=\"margin-right: 5px\"");

WriteLiteralTo(__razor_helper_writer, " />\r\n            </div>\r\n        </th>\r\n");

    }
    else
    {

WriteLiteralTo(__razor_helper_writer, "        <th>");

WriteTo(__razor_helper_writer, title);

WriteLiteralTo(__razor_helper_writer, "</th>\r\n");

    }


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult TableFieldConvention(System.Web.Mvc.HtmlHelper helper, string modelName, string fieldName, object model)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <td>\r\n");

WriteLiteralTo(__razor_helper_writer, "        ");

WriteTo(__razor_helper_writer, helper.Partial(modelName + "/TableView/" + fieldName, model));

WriteLiteralTo(__razor_helper_writer, "\r\n    </td>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult TableFieldFixedView(System.Web.Mvc.HtmlHelper helper, string view, object model)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <td>\r\n");

WriteLiteralTo(__razor_helper_writer, "        ");

WriteTo(__razor_helper_writer, helper.Partial(view, model));

WriteLiteralTo(__razor_helper_writer, "\r\n    </td>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
