#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NotLimited.Framework.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal class IconHelpers : System.Web.WebPages.HelperPage
    {

#line default
#line hidden
public static System.Web.WebPages.HelperResult SimpleIcon(string icon)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 186), Tuple.Create("\"", 205)
, Tuple.Create(Tuple.Create("", 194), Tuple.Create("fa", 194), true)
, Tuple.Create(Tuple.Create(" ", 196), Tuple.Create("fa-", 197), true)
, Tuple.Create(Tuple.Create("", 200), Tuple.Create<System.Object, System.Int32>(icon
, 200), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult IconMargin(string icon)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 260), Tuple.Create("\"", 291)
, Tuple.Create(Tuple.Create("", 268), Tuple.Create("fa", 268), true)
, Tuple.Create(Tuple.Create(" ", 270), Tuple.Create("fa-margin-r", 271), true)
, Tuple.Create(Tuple.Create(" ", 282), Tuple.Create("fa-", 283), true)
, Tuple.Create(Tuple.Create("", 286), Tuple.Create<System.Object, System.Int32>(icon
, 286), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult IconText(string icon, string text)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <span><i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 363), Tuple.Create("\"", 394)
, Tuple.Create(Tuple.Create("", 371), Tuple.Create("fa", 371), true)
, Tuple.Create(Tuple.Create(" ", 373), Tuple.Create("fa-margin-r", 374), true)
, Tuple.Create(Tuple.Create(" ", 385), Tuple.Create("fa-", 386), true)
, Tuple.Create(Tuple.Create("", 389), Tuple.Create<System.Object, System.Int32>(icon
, 389), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>");

                   WriteTo(__razor_helper_writer, text);

WriteLiteralTo(__razor_helper_writer, "</span>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
