#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class IconHelpers
    {

public static System.Web.WebPages.HelperResult SimpleIcon(string icon)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 4 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <i class=\"fa fa-");



#line 5 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, icon);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i>\r\n");



#line 6 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult IconMargin(string icon)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 9 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <i class=\"fa fa-margin-r fa-");



#line 10 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, icon);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i>\r\n");



#line 11 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult IconText(string icon, string text)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 14 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <span><i class=\"fa fa-margin-r fa-");



#line 15 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, icon);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i>");



#line 15 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"
      WebViewPage.WriteTo(@__razor_helper_writer, text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 16 "..\..\Views\Shared\Helpers\IconHelpers.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
