#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
    using NotLimited.Framework.Data.Queries;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
    using NotLimited.Framework.Web.Controls.Grid;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
    using NotLimited.Framework.Web.Views.Shared.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class TableViewHelper
    {

public static System.Web.WebPages.HelperResult TableHeader(System.Web.Mvc.HtmlHelper helper, PropertyMetadata prop, string title, HashSet<string> enabledFields, TableHelpers.SortOrder sortOrder)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 9 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
 
    if (enabledFields == null || enabledFields.Contains(prop.PropertyInfo.Name))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <th class=\"");



#line 12 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, prop.Sortable ? "sortable" : null);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n\r\n            ");



#line 14 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, title);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n\r\n");



#line 16 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
             if (prop.Sortable)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <div class=\"pull-right\">\r\n                    <span class=\"fa ");



#line 19 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, TableHelpers.GetSortIcon(sortOrder));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" style=\"margin-right: 5px\" />\r\n                </div>\r\n");



#line 21 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
                using (helper.BeginForm(null, null, FormMethod.Get))
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <input type=\"hidden\" name=\"sortBy\" value=\"");



#line 23 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
                   WebViewPage.WriteTo(@__razor_helper_writer, prop.PropertyInfo.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <input type=\"hidden\" name=\"descending\" value=\"");



#line 24 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
                       WebViewPage.WriteTo(@__razor_helper_writer, TableHelpers.IsOppositeOrderDescending(sortOrder).ToString());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



#line 25 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
                    
#line default
#line hidden


#line 25 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, FilterViewHelper.HiddenForQuery(helper, "sortBy", "descending"));

#line default
#line hidden


#line 25 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
                                                                                    
                }
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </th>\r\n");



#line 29 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult TableFieldConvention(System.Web.Mvc.HtmlHelper helper, string modelName, string fieldName, object model)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 33 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <td>\r\n        ");



#line 35 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, helper.Partial(modelName + "/TableView/" + fieldName, model));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    </td>\r\n");



#line 37 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult TableFieldFixedView(System.Web.Mvc.HtmlHelper helper, string view, object model)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 40 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <td>\r\n        ");



#line 42 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, helper.Partial(view, model));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    </td>\r\n");



#line 44 "..\..\Views\Shared\Helpers\TableViewHelper.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
