#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotLimited.Framework.Web.Views.Shared.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NotLimited.Framework.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal class IconHelpers : System.Web.WebPages.HelperPage
    {

#line default
#line hidden
public static System.Web.WebPages.HelperResult SimpleIcon(string icon)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 186), Tuple.Create("\"", 205)
, Tuple.Create(Tuple.Create("", 194), Tuple.Create("fa", 194), true)
, Tuple.Create(Tuple.Create(" ", 196), Tuple.Create("fa-", 197), true)
, Tuple.Create(Tuple.Create("", 200), Tuple.Create<System.Object, System.Int32>(icon
, 200), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult SimpleIcon2X(string icon)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 262), Tuple.Create("\"", 287)
, Tuple.Create(Tuple.Create("", 270), Tuple.Create("fa", 270), true)
, Tuple.Create(Tuple.Create(" ", 272), Tuple.Create("fa-", 273), true)
, Tuple.Create(Tuple.Create("", 276), Tuple.Create<System.Object, System.Int32>(icon
, 276), false)
, Tuple.Create(Tuple.Create(" ", 281), Tuple.Create("fa-2x", 282), true)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult IconMargin(string icon)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 342), Tuple.Create("\"", 373)
, Tuple.Create(Tuple.Create("", 350), Tuple.Create("fa", 350), true)
, Tuple.Create(Tuple.Create(" ", 352), Tuple.Create("fa-margin-r", 353), true)
, Tuple.Create(Tuple.Create(" ", 364), Tuple.Create("fa-", 365), true)
, Tuple.Create(Tuple.Create("", 368), Tuple.Create<System.Object, System.Int32>(icon
, 368), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult IconText(string icon, string text)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <span><i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 445), Tuple.Create("\"", 476)
, Tuple.Create(Tuple.Create("", 453), Tuple.Create("fa", 453), true)
, Tuple.Create(Tuple.Create(" ", 455), Tuple.Create("fa-margin-r", 456), true)
, Tuple.Create(Tuple.Create(" ", 467), Tuple.Create("fa-", 468), true)
, Tuple.Create(Tuple.Create("", 471), Tuple.Create<System.Object, System.Int32>(icon
, 471), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>");

                   WriteTo(__razor_helper_writer, text);

WriteLiteralTo(__razor_helper_writer, "</span>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult IconText(string icon, IHtmlString text)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "    <span><i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 565), Tuple.Create("\"", 596)
, Tuple.Create(Tuple.Create("", 573), Tuple.Create("fa", 573), true)
, Tuple.Create(Tuple.Create(" ", 575), Tuple.Create("fa-margin-r", 576), true)
, Tuple.Create(Tuple.Create(" ", 587), Tuple.Create("fa-", 588), true)
, Tuple.Create(Tuple.Create("", 591), Tuple.Create<System.Object, System.Int32>(icon
, 591), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>");

                   WriteTo(__razor_helper_writer, text);

WriteLiteralTo(__razor_helper_writer, "</span>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
